name: Build and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  prepare-variables:
    runs-on: ubuntu-latest
    steps:
      - id: tag_build_number
        run: echo "tag=$(echo ${{ github.head_ref || github.ref_name }} | tr -cs 'a-zA-Z0-9' '-')$(date +'%Y%m%d%H%M%S')-${{ github.run_number }}" >> $GITHUB_OUTPUT
      - id: tag_snapshot
        run: echo "tag=$(echo ${{ github.head_ref || github.ref_name }} | tr -cs 'a-zA-Z0-9' '-')snapshot" >> $GITHUB_OUTPUT
    outputs:
      tag_build_number: ${{ steps.tag_build_number.outputs.tag }}
      tag_snapshot: ${{ steps.tag_snapshot.outputs.tag }}
      repo: ${{ steps.repo.outputs.repo }}
  build:
    runs-on: ubuntu-latest
    needs: prepare-variables
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Test with coverage
      run: |
        cd maas-service
        go test -v ./... -coverprofile coverage.out

    - name: Upload coverage report to SonarCloud
      uses: SonarSource/sonarqube-scan-action@v5
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
       args: >
         -Dproject.settings=maas-service/sonar-project.properties
         -Dsonar.projectKey=TaurMorchant_qubership-maas-tmp
         -Dsonar.organization=vladislav-larkin-test-organization
         -Dsonar.go.coverage.reportPaths=maas-service/coverage.out